# Generated by Django 4.2.30 on 2026-05-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuseracct',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuseracct',
            name='phone_num',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
